spring:
  application:
    name: planner

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PL_DB_USER}
    password: ${PL_DB_PWD}
    url: jdbc:postgresql://${PL_DB_URL}/${PL_DB_NAME}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
    open-in-view: false

  mail:
    host: ${PL_MAIL_HOST}
    port: ${PL_MAIL_PORT}
    username: ${PL_MAIL_USERNAME}
    password: ${PL_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${PL_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${PL_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

server:
  servlet:
    context-path: /planner/api
  port: ${PL_APP_PORT}

jwt:
  access-key: ${PL_JWT_ACCESS_KEY}
  refresh-private-key: ${PL_JWT_REFRESH_PRIVATE_KEY}
  refresh-public-key: ${PL_JWT_REFRESH_PUBLIC_KEY}
  access-expire: ${PL_JWT_ACCESS_EXPIRE}
  refresh-expire: ${PL_JWT_REFRESH_EXPIRE}
