name: Deploy Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set dummy environment variables for build
        run: |
          echo "PL_DB_USER=dummy_user" >> $GITHUB_ENV
          echo "PL_DB_PWD=dummy_pwd" >> $GITHUB_ENV
          echo "PL_DB_URL=localhost:5432" >> $GITHUB_ENV
          echo "PL_DB_NAME=planner_db" >> $GITHUB_ENV

          echo "PL_MAIL_HOST=smtp.example.com" >> $GITHUB_ENV
          echo "PL_MAIL_PORT=587" >> $GITHUB_ENV
          echo "PL_MAIL_USERNAME=dummy_mail_user" >> $GITHUB_ENV
          echo "PL_MAIL_PASSWORD=dummy_mail_pwd" >> $GITHUB_ENV
          echo "PL_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true" >> $GITHUB_ENV
          echo "PL_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true" >> $GITHUB_ENV
          echo "PL_MAIL_PATH_HOME=/dummy/home" >> $GITHUB_ENV
          echo "PL_MAIL_PATH_PASSWORD=/dummy/password" >> $GITHUB_ENV

          echo "PL_REDIS_HOST=localhost" >> $GITHUB_ENV
          echo "PL_REDIS_PORT=6379" >> $GITHUB_ENV
          echo "PL_REDIS_EXPIRE_PASSWORD=600" >> $GITHUB_ENV

          echo "PL_MQ_HOST=localhost" >> $GITHUB_ENV
          echo "PL_MQ_PORT=5672" >> $GITHUB_ENV
          echo "PL_MQ_STOMP=15674" >> $GITHUB_ENV
          echo "PL_MQ_DOMAIN=dummy.domain" >> $GITHUB_ENV
          echo "PL_MQ_USER=dummy_mq_user" >> $GITHUB_ENV
          echo "PL_MQ_PASSWORD=dummy_mq_pwd" >> $GITHUB_ENV

          echo "PL_MQ_FRIEND_EXCHANGE=friend.exchange" >> $GITHUB_ENV
          echo "PL_MQ_FRIEND_REQUEST_ROUTING=friend.request.routing" >> $GITHUB_ENV
          echo "PL_MQ_BOARD_EXCHANGE=board.exchange" >> $GITHUB_ENV
          echo "PL_MQ_BOARD_COMMENT_ROUTING=board.comment.routing" >> $GITHUB_ENV
          echo "PL_MQ_SCH_EXCHANGE=schedule.exchange" >> $GITHUB_ENV
          echo "PL_MQ_SCH_REQUEST_ROUTING=schedule.request.routing" >> $GITHUB_ENV

          echo "PL_APP_PORT=8080" >> $GITHUB_ENV

          echo "PL_JWT_ACCESS_KEY=dummy_access_key" >> $GITHUB_ENV
          echo "PL_JWT_REFRESH_PRIVATE_KEY=dummy_refresh_private_key" >> $GITHUB_ENV
          echo "PL_JWT_REFRESH_PUBLIC_KEY=dummy_refresh_public_key" >> $GITHUB_ENV
          echo "PL_SYS_APP_KEY=dummy_sys_key" >> $GITHUB_ENV
          echo "PL_JWT_ACCESS_EXPIRE=3600" >> $GITHUB_ENV
          echo "PL_JWT_REFRESH_EXPIRE=604800" >> $GITHUB_ENV

          echo "PL_LOG_PATH=/var/log/planner" >> $GITHUB_ENV            

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootjar

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build docker image
        run: docker build -f docker/Dockerfile -t planner:latest .

      - name: Tag Docker image
        run: docker tag planner:latest ojw25/planner:latest

      - name: Push Docker image
        run: docker push ojw25/planner:latest

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: SSH into server and run kubectl
        run: |
          ssh -i id_rsa -o StrictHostKeyChecking=no \
            -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "${{ secrets.DEPLOY_COMMAND }}"

      - name: Clean up SSH key
        run: rm -f id_rsa
